//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace md5sum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("md5sum.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: no such file or directory with this name..
        /// </summary>
        internal static string err_file_dir_not_found {
            get {
                return ResourceManager.GetString("err_file_dir_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown option &quot;{0}&quot;..
        /// </summary>
        internal static string err_option {
            get {
                return ResourceManager.GetString("err_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        internal static string text_failed {
            get {
                return ResourceManager.GetString("text_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisation: md5sum [OPTION]... [FICHIER]...
        ///Affiche ou vérifie les sommes de contrôle MD5 d&apos;un ou plusieurs fichiers.
        ///Si aucun fichier n&apos;est indiqué, l&apos;entrée standard est utilisée.
        ///
        ///    -c, --check    lit les sommes MD5 à partir du ou des fichiers indiqués
        ///        --tag      crée une somme de contrôle de type BSD
        ///    /?, --help     affiche cette aide
        ///        --version  affiche la version de l&apos;outil
        ///
        ///Les options ci-dessous ne sont utilisées que lors d&apos;une vérification:
        ///        --quiet    ne pas a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_help {
            get {
                return ResourceManager.GetString("text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sommes de contrôle ne correspondent pas..
        /// </summary>
        internal static string text_multi_files_checksum_error {
            get {
                return ResourceManager.GetString("text_multi_files_checksum_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string text_ok {
            get {
                return ResourceManager.GetString("text_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} somme de contrôle ne correspond pas..
        /// </summary>
        internal static string text_one_file_checksum_error {
            get {
                return ResourceManager.GetString("text_one_file_checksum_error", resourceCulture);
            }
        }
    }
}
